site_name: Simulacra Documentation

theme: readthedocs

nav:
  - Home: index.md
  - API Documentation: api.md
  - Simulations:
      - Product Popularity: product_popularity.md
      - Stock Market: stock_market.md
      - Resource Fluctuations: resource_fluctuations.md
  - Getting Started: getting_started.md
  - Contribute: contribute.md
  - Contact: contact.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true