site_name: Simulacra Documentation
nav:
    - Home: index.md
    - API Documentation: api.md
plugins:
    - search
    - mkdocstrings:
        handlers:
          python:
            rendering:
              show_source: true
