name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    
    - name: Lint with flake8
      run: |
        poetry run flake8 simulacra/


    - name: Type check
      run: |
        poetry run mypy simulacra
    
    - name: Run tests with pytest
      run: |
        poetry run pytest

    - name: Build MkDocs Documentation
      run: |
        poetry run mkdocs build
        touch site/.nojekyll 

    - name: Deploy MkDocs Documentation
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site

    - name: Build and publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
